export type Parcel = {
  id: string;
  icon: string;
  name: string;
  category: string;
  price: string;
  priceNumber: number;
  bg: string;
  badge: string | null;
  badgeColor: string;
  desc: string;
  longDesc: string;
  includes: string[];
  sizeOptions: { label: string; price: string }[];
  occasions: string[];
  notes: string;
};

export const parcels: Parcel[] = [
  {
    id: 'parcel-segar-s',
    icon: '🧺',
    name: 'Parcel Buah Segar S',
    category: 'Buah Segar',
    price: 'Mulai Rp 120.000',
    priceNumber: 120000,
    bg: '#fff7ed',
    badge: 'Terlaris',
    badgeColor: '#f59e0b',
    desc: 'Berisi 5 buah segar pilihan dalam keranjang anyaman cantik.',
    longDesc: 'Parcel buah segar ukuran Small cocok untuk berbagai kesempatan. Berisi 5 jenis buah pilihan yang segar dan berkualitas, dikemas dalam keranjang anyaman cantik dengan ribbon elegan. Setiap buah melewati quality check ketat sebelum dikemas.',
    includes: ['Jeruk Pontianak 500gr', 'Mangga Harum Manis 500gr', 'Apel Fuji 3 buah', 'Anggur Merah 250gr', 'Pir Hijau 2 buah', 'Keranjang anyaman', 'Ribbon & kartu ucapan'],
    sizeOptions: [
      { label: 'Small (5 buah)', price: 'Rp 120.000' },
      { label: 'Custom isi', price: 'Hubungi kami' },
    ],
    occasions: ['Ulang tahun', 'Pernikahan', 'Arisan', 'Hampers biasa'],
    notes: 'Ketersediaan buah menyesuaikan musim. Kami akan konfirmasi substitusi jika ada.',
  },
  {
    id: 'parcel-segar-m',
    icon: '🧺',
    name: 'Parcel Buah Segar M',
    category: 'Buah Segar',
    price: 'Mulai Rp 220.000',
    priceNumber: 220000,
    bg: '#fff7ed',
    badge: null,
    badgeColor: '',
    desc: 'Berisi 8 buah segar pilihan dengan kemasan premium.',
    longDesc: 'Parcel buah segar ukuran Medium adalah pilihan paling populer. Berisi 8 jenis buah pilihan yang segar dan berkualitas tinggi, dikemas dalam keranjang anyaman premium dengan sentuhan elegan yang memukau.',
    includes: ['Jeruk Pontianak 500gr', 'Mangga Harum Manis 500gr', 'Strawberry 250gr', 'Anggur Merah 250gr', 'Pir Hijau 2 buah', 'Apel Fuji 3 buah', 'Kiwi 3 buah', 'Melon 1 buah', 'Keranjang anyaman premium', 'Ribbon & kartu ucapan'],
    sizeOptions: [
      { label: 'Medium (8 buah)', price: 'Rp 220.000' },
      { label: 'Custom isi', price: 'Hubungi kami' },
    ],
    occasions: ['Ulang tahun', 'Wisuda', 'Pernikahan', 'Get well soon'],
    notes: 'Tersedia same-day delivery untuk wilayah Malang kota.',
  },
  {
    id: 'parcel-segar-l',
    icon: '🧺',
    name: 'Parcel Buah Segar L',
    category: 'Buah Segar',
    price: 'Mulai Rp 380.000',
    priceNumber: 380000,
    bg: '#fff7ed',
    badge: 'Premium',
    badgeColor: '#1a5c2e',
    desc: 'Berisi 12 buah segar pilihan dalam keranjang besar elegan.',
    longDesc: 'Parcel buah segar ukuran Large adalah pilihan mewah untuk kesan yang tak terlupakan. Berisi 12 jenis buah premium yang dikemas dalam keranjang besar elegan dengan dekorasi premium.',
    includes: ['12 buah pilihan premium', 'Keranjang anyaman besar', 'Ribbon eksklusif', 'Kartu ucapan premium', 'Wrapping cantik', 'Bisa request buah tertentu'],
    sizeOptions: [
      { label: 'Large (12 buah)', price: 'Rp 380.000' },
      { label: 'Extra Large (15 buah)', price: 'Rp 480.000' },
      { label: 'Custom isi', price: 'Hubungi kami' },
    ],
    occasions: ['Anniversary', 'Pernikahan', 'Corporate gift', 'Ulang tahun spesial'],
    notes: 'Untuk pemesanan corporate (10+ parcel) tersedia diskon khusus.',
  },
  {
    id: 'parcel-eksotis',
    icon: '🍇',
    name: 'Parcel Buah Eksotis',
    category: 'Buah Eksotis',
    price: 'Mulai Rp 350.000',
    priceNumber: 350000,
    bg: '#faf5ff',
    badge: 'Eksklusif',
    badgeColor: '#7c3aed',
    desc: 'Koleksi buah eksotis import pilihan dalam kemasan mewah.',
    longDesc: 'Parcel Buah Eksotis menghadirkan koleksi buah-buahan premium import yang langka dan mewah. Setiap buah dipilih dengan teliti untuk memastikan kualitas terbaik. Hadiah yang benar-benar berkesan untuk orang istimewa.',
    includes: ['Shine Muscat Import 500gr', 'Persik Import 3 buah', 'Blueberry Fresh 250gr', 'Strawberry Premium 250gr', 'Anggur Hijau Seedless 250gr', 'Keranjang premium', 'Ribbon eksklusif', 'Kartu ucapan'],
    sizeOptions: [
      { label: 'Standard (5 buah eksotis)', price: 'Rp 350.000' },
      { label: 'Premium (7 buah eksotis)', price: 'Rp 550.000' },
      { label: 'Custom isi', price: 'Hubungi kami' },
    ],
    occasions: ['Hadiah mewah', 'Anniversary', 'Corporate gift', 'Ulang tahun spesial'],
    notes: 'Ketersediaan buah import terbatas. Disarankan pesan H-2 untuk memastikan stok.',
  },
  {
    id: 'parcel-ultah',
    icon: '🎂',
    name: 'Parcel Ulang Tahun',
    category: 'Ulang Tahun',
    price: 'Mulai Rp 280.000',
    priceNumber: 280000,
    bg: '#fef3c7',
    badge: 'Spesial',
    badgeColor: '#f59e0b',
    desc: 'Rayakan hari spesial dengan parcel buah premium berdekorasi ulang tahun.',
    longDesc: 'Parcel Ulang Tahun Healthila hadir untuk membuat hari spesialmu semakin berkesan. Kombinasi buah premium dengan dekorasi ulang tahun yang meriah — hadiah sehat yang tetap terasa mewah dan penuh kasih sayang.',
    includes: ['8 buah pilihan premium', 'Dekorasi balon mini', 'Kartu ucapan HBD custom', 'Ribbon warna-warni', 'Box premium', 'Bisa tambah jus cold-pressed'],
    sizeOptions: [
      { label: 'Standard (8 buah)', price: 'Rp 280.000' },
      { label: 'Premium (12 buah)', price: 'Rp 420.000' },
      { label: 'Custom isi', price: 'Hubungi kami' },
    ],
    occasions: ['Ulang tahun anak', 'Ulang tahun dewasa', 'Sweet 17', 'Milestone birthday'],
    notes: 'Bisa tambahkan nama dan pesan personal di kartu ucapan. Gratis!',
  },
  {
    id: 'parcel-getwellsoon',
    icon: '💚',
    name: 'Parcel Get Well Soon',
    category: 'Get Well Soon',
    price: 'Mulai Rp 200.000',
    priceNumber: 200000,
    bg: '#f0fdf4',
    badge: 'Menyehatkan',
    badgeColor: '#1a5c2e',
    desc: 'Tunjukkan kepedulianmu dengan parcel buah segar menyehatkan.',
    longDesc: 'Parcel Get Well Soon dirancang khusus untuk mendukung pemulihan orang yang kita sayangi. Berisi buah-buahan tinggi vitamin C dan antioksidan, dilengkapi jus cold-pressed yang menyehatkan.',
    includes: ['Jeruk Vitamin C tinggi 1kg', 'Jus Cold-Pressed 2 botol', 'Madu alami 1 botol', 'Apel Fuji 3 buah', 'Kiwi 3 buah', 'Kartu ucapan hangat', 'Kemasan ramah'],
    sizeOptions: [
      { label: 'Basic (buah + jus)', price: 'Rp 200.000' },
      { label: 'Complete (+ madu & suplemen)', price: 'Rp 320.000' },
      { label: 'Custom isi', price: 'Hubungi kami' },
    ],
    occasions: ['Sakit', 'Pasca operasi', 'Pemulihan', 'Doa kesembuhan'],
    notes: 'Tersedia pengiriman ke rumah sakit. Hubungi kami untuk konfirmasi.',
  },
  {
    id: 'parcel-lebaran',
    icon: '🌙',
    name: 'Parcel Lebaran Premium',
    category: 'Lebaran',
    price: 'Mulai Rp 320.000',
    priceNumber: 320000,
    bg: '#fef3c7',
    badge: 'Edisi Lebaran',
    badgeColor: '#d97706',
    desc: 'Sambut Lebaran dengan parcel buah premium bernuansa Islami.',
    longDesc: 'Parcel Lebaran Premium Healthila hadir untuk mempererat silaturahmi di momen Idul Fitri. Dikemas cantik dengan nuansa Islami yang elegan, berisi buah-buahan premium dan kurma pilihan.',
    includes: ['Kurma premium 500gr', 'Buah segar 6 jenis', 'Kemasan nuansa Lebaran', 'Kartu ucapan Idul Fitri', 'Ribbon emas', 'Box premium'],
    sizeOptions: [
      { label: 'Standard (6 buah + kurma)', price: 'Rp 320.000' },
      { label: 'Premium (10 buah + kurma)', price: 'Rp 500.000' },
      { label: 'Corporate (min. 10 pcs)', price: 'Hubungi kami' },
    ],
    occasions: ['Idul Fitri', 'Idul Adha', 'Silaturahmi', 'Hampers kantor'],
    notes: 'Pemesanan Lebaran dibuka 2 minggu sebelum hari H. Stok terbatas!',
  },
  {
    id: 'parcel-bunga-hampers',
    icon: '💐',
    name: 'Parcel Bunga & Hampers',
    category: 'Bunga & Hampers',
    price: 'Mulai Rp 400.000',
    priceNumber: 400000,
    bg: '#fdf2f8',
    badge: 'Romantis',
    badgeColor: '#db2777',
    desc: 'Kombinasi bunga segar dan buah premium dalam satu hampers elegan.',
    longDesc: 'Parcel Bunga & Hampers adalah hadiah paling romantis dan berkesan. Kombinasi sempurna antara rangkaian bunga segar yang indah dan buah-buahan eksotis premium dalam satu hampers mewah.',
    includes: ['Rangkaian bunga segar (10-15 tangkai)', 'Buah eksotis 4 jenis', 'Box hampers premium', 'Pita satin', 'Kartu ucapan eksklusif', 'Bisa custom warna bunga'],
    sizeOptions: [
      { label: 'Romantic (bunga + 4 buah)', price: 'Rp 400.000' },
      { label: 'Grand (bunga besar + 6 buah)', price: 'Rp 650.000' },
      { label: 'Custom tema', price: 'Hubungi kami' },
    ],
    occasions: ['Valentine', 'Anniversary', 'Pernikahan', 'Wisuda', 'Ulang tahun'],
    notes: 'Jenis bunga menyesuaikan ketersediaan. Bisa request warna tema tertentu.',
  },
  {
    id: 'parcel-coldpressed',
    icon: '🥤',
    name: 'Hampers Cold-Pressed',
    category: 'Cold-Pressed',
    price: 'Mulai Rp 250.000',
    priceNumber: 250000,
    bg: '#f0fdf4',
    badge: 'Healthy',
    badgeColor: '#059669',
    desc: 'Hampers eksklusif berisi botol-botol jus cold-pressed premium.',
    longDesc: 'Hampers Cold-Pressed adalah hadiah gaya hidup sehat yang paling trendi. Berisi botol-botol jus cold-pressed premium tanpa gula tambahan, tanpa pengawet, dengan nutrisi terjaga maksimal.',
    includes: ['6 botol jus cold-pressed (350ml)', 'Berbagai rasa (jeruk, hijau, merah, dll)', 'Tanpa gula tambahan', 'Tanpa pengawet', 'Box premium', 'Kartu edukasi gizi'],
    sizeOptions: [
      { label: 'Mini (3 botol)', price: 'Rp 150.000' },
      { label: 'Standard (6 botol)', price: 'Rp 250.000' },
      { label: 'Premium (12 botol)', price: 'Rp 450.000' },
    ],
    occasions: ['Hadiah sehat', 'Detox program', 'Corporate wellness', 'Ulang tahun'],
    notes: 'Cold-pressed harus disimpan dalam kulkas. Ketahanan 3-5 hari setelah diproduksi.',
  },
  {
    id: 'fruit-cake-semangka',
    icon: '🍉',
    name: 'Fruit Cake Semangka',
    category: 'Fruit Cake',
    price: 'Mulai Rp 180.000',
    priceNumber: 180000,
    bg: '#fff1f2',
    badge: 'Unik',
    badgeColor: '#e11d48',
    desc: 'Kreasi unik cake dari semangka yang didekorasi buah-buahan segar.',
    longDesc: 'Fruit Cake Semangka adalah kreasi unik dan sehat dari Healthila. Dibuat dari semangka segar utuh yang dibentuk layaknya kue, lalu didekorasi dengan berbagai buah-buahan segar warna-warni. Pengganti kue ulang tahun yang jauh lebih sehat!',
    includes: ['Semangka segar 5-7kg', 'Dekorasi strawberry & kiwi', 'Blueberry & anggur', 'Topping mangga', 'Tanpa tepung & gula tambahan', 'Box cantik', 'Lilin ulang tahun (request)'],
    sizeOptions: [
      { label: 'Small (semangka 3kg)', price: 'Rp 180.000' },
      { label: 'Medium (semangka 5kg)', price: 'Rp 250.000' },
      { label: 'Large (semangka 7kg)', price: 'Rp 350.000' },
    ],
    occasions: ['Ulang tahun anak', 'Baby shower', 'Acara sehat', 'Gathering'],
    notes: 'Fruit cake dibuat fresh dan harus segera dikonsumsi pada hari yang sama.',
  },
  {
    id: 'parcel-custom',
    icon: '✨',
    name: 'Parcel Custom',
    category: 'Custom',
    price: 'Harga sesuai request',
    priceNumber: 0,
    bg: '#e8f5e9',
    badge: 'Custom',
    badgeColor: '#1a5c2e',
    desc: 'Buat parcel sesuai keinginanmu sendiri!',
    longDesc: 'Dengan layanan Parcel Custom Healthila, kamu bisa menentukan sendiri isi, kemasan, tema, dan dekorasi parcelmu. Tim kami siap membantu mewujudkan parcel impianmu sesuai budget dan kebutuhan.',
    includes: ['Buah sesuai pilihan kamu', 'Kemasan custom sesuai tema', 'Dekorasi sesuai request', 'Kartu ucapan personal', 'Bisa antar ke lokasi', 'Konsultasi gratis'],
    sizeOptions: [
      { label: 'Budget Rp 100rb - 200rb', price: 'Hubungi kami' },
      { label: 'Budget Rp 200rb - 500rb', price: 'Hubungi kami' },
      { label: 'Budget > Rp 500rb', price: 'Hubungi kami' },
    ],
    occasions: ['Semua kesempatan', 'Corporate order', 'Wedding favor', 'Event khusus'],
    notes: 'Untuk pemesanan custom, minimal H-3 sebelum tanggal dibutuhkan.',
  },
];

export function getParcelById(id: string): Parcel | undefined {
  return parcels.find((p) => p.id === id);
}